services:
  attacker_system:
    image: dc3lik/attacker_system:latest
    container_name: attacker_system
    hostname: attacker_system
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10022:22"
      
  target_file_inclusion:
    image: dc3lik/target_file_inclusion:latest
    container_name: target_file_inclusion
    hostname: target_file_inclusion
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10081:80"
networks:
  dc_network:
    driver: bridge
