services:
  attacker_system:
    image: dc3lik/attacker_system:latest
    container_name: attacker_system
    hostname: attacker_system
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10022:22"
      
  target_public1:
    image: dc3lik/target_public1:latest
    container_name: target_public1
    hostname: target_public1
    networks:
      - dc_network
 
networks:
  dc_network:
    driver: bridge
