services:
  attacker_system:
    image: dc3lik/attacker_system:latest
    container_name: attacker_system
    hostname: attacker_system
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10022:22"

  target_lpe1:
    image: dc3lik/target_lpe1:latest
    container_name: target_lpe1
    hostname: target_lpe1
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20022:22"
      
  target_lpe2:
    image: dc3lik/target_lpe2:latest
    container_name: target_lpe2
    hostname: target_lpe2
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20023:22"

  target_lpe3:
    image: dc3lik/target_lpe3:latest
    container_name: target_lpe3
    hostname: target_lpe3
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20024:22"

  target_lpe4:
    image: dc3lik/target_lpe4:latest
    container_name: target_lpe4
    hostname: target_lpe4
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20025:22"

  target_lpe5:
    image: dc3lik/target_lpe5:latest
    container_name: target_lpe5
    hostname: target_lpe5
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20026:22"

  target_lpe6:
    image: dc3lik/target_lpe6:latest
    container_name: target_lpe6
    hostname: target_lpe6
    networks:
      - dc_network
    ports:
      - "127.0.0.1:20027:22"

networks:
  dc_network:
    driver: bridge
