services:
  attacker_system:
    image: dc3lik/attacker_system:latest
    container_name: attacker_system
    hostname: attacker_system
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10022:22"

  target_pass_atks:
    image: dc3lik/target_pass_atks:latest
    container_name: target_pass_atks
    hostname: target_pass_atks
    networks:
      - dc_network


networks:
  dc_network:
    driver: bridge
